# Generated by Django 3.1.7 on 2021-03-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='update time'),
        ),
    ]
